id: kubelet-healthz
info:
  name: Kubelet Healthz
  author: sharath
  description: Scans for kubelet healthz
  severity: info
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kubelet
traps:
- request:
    method: GET
    path: /healthz
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: text/plainKubernetes
    body: ok
