id: openapi
info:
  name: OpenAPI - Detect
  author: pdteam,ynnirc
  description: OpenAPI was detected.
  severity: info
  reference:
  - https://www.openapis.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,api
traps:
- request:
    method: GET
    path: /openapi.json
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: application/openapi+jsonapplication/json
    body: openapipaths
