id: cors-misconfig
info:
  name: CORS Misconfiguration
  author: nadino,g4l1t0,convisoappsec,pdteam,breno_css,nodauf
  description: null
  severity: info
  reference:
  - https://portswigger.net/web-security/cors
  - https://www.corben.io/advanced-cors-techniques/
  - https://www.geekboy.ninja/blog/exploiting-misconfigured-cors-cross-origin-resource-sharing/
  metadata:
    max-request: 11
  tags: cors,generic,misconfig
traps:
- request:
    method: GET
    path: HTTP/1.1
    headers:
      Origin: '{{cors_origin}}'
    body: ''
  response:
    status_code: 200
    headers: {}
    body: ''
