id: kube-api-deployments
info:
  name: Kube API Deployments
  author: sharath
  description: Scans for kube deployments
  severity: info
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube
traps:
- request:
    method: GET
    path: /apis/apps/v1/namespaces/default/deployments
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"DeploymentList":"items":'
