id: kube-api-secrets
info:
  name: Kube API Secrets
  author: sharath
  description: Scans for kube secrets endpoint
  severity: info
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube
traps:
- request:
    method: GET
    path: /api/v1/namespaces/default/secrets
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"SecretList":"items":'
