id: kube-api-version
info:
  name: Kube API Version
  author: sharath,raesene
  description: Searches for exposed Kubernetes API servers which return version information
    unauthenticated
  severity: info
  metadata:
    max-request: 1
  tags: tech,k8s,kubernetes,devops,kube
traps:
- request:
    method: GET
    path: /version
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"major":"minor":"goVersion":'
