id: amp-application-panel
info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  description: Application Management Panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: amp
    shodan-query: title:"AMP - Application Management Panel"
    vendor: cubecoders
    verified: true
  tags: panel,amp,cubecoders
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: text/html
    body: <title>AMP - Application Management Panel</title>
