id: esphome-panel
info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  description: ESPHome login panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: esphome
    shodan-query: title:"Login - ESPHome"
    vendor: esphome
    verified: true
  tags: panel,esphome,iot
traps:
- request:
    method: GET
    path: /login
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: class="esphome-header
