id: extreme-netconfig-ui
info:
  name: Extreme NetConfig UI Panel - Detect
  author: pussycat0x
  description: Extreme NetConfig UI panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
    shodan-query: http.title:"Extreme NetConfig UI"
  tags: panel,tech,hiveos,extreme
traps:
- request:
    method: GET
    path: /index.php5
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <title>Extreme NetConfig UI</title>
