id: prometheus-pushgateway-exposed-panel
info:
  name: Prometheus Pushgateway Panel - Detect
  author: codexlynx
  description: Prometheus Pushgateway panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,prometheus,pushgateway
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <title>Prometheus Pushgateway</title>
