id: sonic-wall-application
info:
  name: SonicWall Appliance Management Console Login Panel - Detect
  author: DhiyaneshDk,Tess
  description: SonicWall Appliance Management Console login panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:o:sonicwall:sma1000_firmware:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: sma1000_firmware
    shodan-query: title:"Appliance Management Console Login"
    vendor: sonicwall
    verified: true
  tags: panel,sonicwall,login
traps:
- request:
    method: GET
    path: /login.do
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <title>Appliance Management Console Login</title>
