id: springboot-loggerconfig
info:
  name: Spring Boot LoggerConfig Actuator Panel - Detect
  author: DhiyaneshDK
  description: Spring Boot LoggerConfig Actuator panel was detected.
  severity: info
  reference:
  - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: title:"Eureka"
  tags: misconfig,springboot,exposure
traps:
- request:
    method: GET
    path: /loggingConfig
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '["loggingConfig"]"propertySources"'
- request:
    method: GET
    path: /actuator/loggingConfig
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
