id: grandstream-device-configuration
info:
  name: Grandstream Device Configuration
  author: dhiyaneshDK
  description: Exposed Grandstream device configuration page detected.
  severity: info
  metadata:
    max-request: 1
    shodan-query: http.title:"Grandstream Device Configuration"
  tags: iot
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <title>Grandstream Device Configuration</title>
