id: raspberry-shake-config
info:
  name: Raspberry Shake Config Detection
  author: pussycat0x
  description: 'The Shake Board digitizer receives, processes, and interprets the
    sensor data in real-time, allowing for the Raspberry Pi computer to export the
    data for easy access. The data output can be displayed and analyzed using our
    own comprehensive set of web tools or any standard seismological software.

    '
  severity: medium
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Raspberry Shake Config"
  tags: misconfig,unauth,iot,raspberry
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Raspberry Shake Config
