id: alibaba-canal-info-leak
info:
  name: Alibaba Canal Config - Detect
  author: pikpikcu
  description: Alibaba Canal configuration information was detected.
  severity: info
  reference:
  - https://github.com/alibaba/canal/issues/632
  - https://netty.io/wiki/reference-counted-objects.html
  - https://my.oschina.net/u/4581879/blog/4753320
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,alibaba
traps:
- request:
    method: GET
    path: /api/v1/canal/config/1/1
    headers:
      Content-Type: application/json
    body: null
  response:
    status_code: 200
    headers: {}
    body: ncanal.aliyun.accessKeyncanal.aliyun.secretKey
