id: aws-credentials
info:
  name: AWS Credentials - Detect
  author: m4lwhere
  description: AWS credentials found via /.aws/credentials endpoint.
  severity: high
  reference:
  - https://aws.amazon.com/blogs/security/what-to-do-if-you-inadvertently-expose-an-aws-access-key/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L
    cvss-score: 9.4
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
  tags: config,exposure,aws,credential
traps:
- request:
    method: GET
    path: /.aws/credentials
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: aws_access_key_id\s*=\s*
