id: babel-config-exposure
info:
  name: Babel Configuration - Detect
  author: DhiyaneshDK
  description: Babel configuration information was detected.
  severity: info
  reference:
  - https://babeljs.io/docs/en/configuration
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"babel.config.js"
  tags: exposure,config,file
traps:
- request:
    method: GET
    path: /babel.config.js
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'module.exports = {presets: ['
