id: cisco-network-config
info:
  name: Cisco System Network Configuration Page - Detect
  author: DhiyaneshDk
  description: Cisco System Network configuration page was detected. Page lists whole
    network configuration and internal logs of Cisco IP phones.
  severity: info
  reference:
  - https://www.exploit-db.com/ghdb/5430
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,cisco,edb,config
traps:
- request:
    method: GET
    path: /CGI/Java/Serviceability?adapter=device.statistics.configuration
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Network Configuration
