id: codeception-config
info:
  name: Codeception YAML Configuration File - Detect
  author: DhiyaneshDk
  description: Codeception YAML configuration file was detected.
  severity: low
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"codeception.yml"
  tags: exposure,devops,codeception,config,cicd
traps:
- request:
    method: GET
    path: /codeception.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'paths:settings:'
