id: cypress-web-config
info:
  name: Cypress Oxygen Configuration Page - Detect
  author: tess
  description: Cypress Oxygen configuration page was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"PendingInstallVZW - Web Page Configuration"
  tags: exposure,cypress,pendinginstallvzw,config
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: PendingInstallVZW - Web Page Configurationalt="Cypress Oxygen-3
