id: dockerfile-hidden-disclosure
info:
  name: Dockerfile - Detect
  author: dhiyaneshDk
  description: Dockerfile was detected.
  severity: medium
  reference:
  - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 3
  tags: exposure,config
traps:
- request:
    method: GET
    path: /.dockerfile
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: text/html
    body: ^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+
- request:
    method: GET
    path: /.Dockerfile
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /Dockerfile
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
