id: exposed-sharepoint-list
info:
  name: Sharepoint List - Detect
  author: ELSFA7110
  description: Sharepoint list was detected because of improper configuration. An
    anonymous user can access SharePoint Web Services.
  severity: medium
  reference:
  - https://hackerone.com/reports/761158
  - https://hackerone.com/reports/300539
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: hackerone,config,exposure,sharepoint
traps:
- request:
    method: GET
    path: /_vti_bin/lists.asmx?WSDL
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: GetListResponseGetList
