id: exposed-darcs
info:
  name: Darcs Configuration - Detect
  author: daffainfo
  description: Darcs configuration was detected.
  severity: info
  reference:
  - http://darcs.net/Using/Configuration#sources
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure
traps:
- request:
    method: GET
    path: /_darcs/prefs/binaries
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Binary file regexps
