id: git-credentials-disclosure
info:
  name: Git Credentials - Detect
  author: dhiyaneshDk
  description: Git credentials were detected.
  severity: medium
  reference:
  - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/git-credentials-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,config
traps:
- request:
    method: GET
    path: /.git-credentials
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: text/html
    body: https://@github.com
