id: gmail-api-client-secrets
info:
  name: GMail API - Detect
  author: geeknik
  description: GMail API was detected.
  severity: info
  reference: https://developers.google.com/gmail/api/auth/web-server
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure
traps:
- request:
    method: GET
    path: /client_secrets.json
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: application/json
    body: client_idauth_uritoken_uri
