id: guard-config
info:
  name: Guardfile Config - Detect
  author: DhiyaneshDK
  description: Guardfile configuration information was detected.
  severity: info
  reference:
  - https://github.com/guard/guard
  - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Guardfile"
  tags: exposure,file,guard,config
traps:
- request:
    method: GET
    path: /Guardfile
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: guard :end
