id: hp-ilo-serial-key-disclosure
info:
  name: HP iLO Serial Key - Detect
  author: dhiyaneshDk
  description: HP iLO serial key was detected.
  severity: medium
  reference:
  - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/hp-ilo-serial-key-disclosure.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: exposure,config
traps:
- request:
    method: GET
    path: /xmldata?item=CpqKey
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: LTYPELNAMEKEY
