id: htpasswd-detection
info:
  name: Apache htpasswd Config - Detect
  author: geeknik
  description: Apache htpasswd configuration was detected.
  severity: high
  reference: https://httpd.apache.org/docs/current/programs/htpasswd.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure
traps:
- request:
    method: GET
    path: /.htpasswd
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: :{SHA}:$apr1$:$2y$
