id: httpd-config
info:
  name: Apache httpd Config File - Detect
  author: sheikhrishad
  description: Apache httpd configuration information was detected.
  severity: info
  reference: https://httpd.apache.org/docs/current/configuring.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,httpd
traps:
- request:
    method: GET
    path: /httpd.conf
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: LoadModule# LoadModule
