id: jetbrains-datasource
info:
  name: Jetbrains IDE DataSources Config - Detect
  author: FlorianMaak
  description: Jetbrains IDE DataSources configuration information was detected.
  severity: info
  reference: https://www.jetbrains.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,jetbrains
traps:
- request:
    method: GET
    path: /.idea/dataSources.xml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: DataSourceManagerImpl
