id: keycloak-openid-config
info:
  name: Keycloak OpenID Configuration - Detect
  author: rodnt
  description: Keycloak Openid configuration information was detected.
  severity: info
  reference:
  - https://issues.jboss.org/browse/KEYCLOAK-571
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: keycloak,config,exposure
traps:
- request:
    method: GET
    path: /.well-known/openid-configuration
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: issuerauthorization_endpointtoken_endpointuserinfo_endpointjwks_uri
- request:
    method: GET
    path: /auth/realms/master/.well-known/openid-configuration
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
