id: magento-config-disclosure
info:
  name: Magento Configuration Panel - Detect
  author: ptonewreckin,danigoland,geeknik
  description: 'Magento configuration panel was detected. Misconfigured instances
    of Magento may disclose usernames, passwords, and database configurations via
    /app/etc/local.xml.

    '
  severity: high
  reference:
  - https://github.com/ptonewreckin/cmsDetector/blob/master/signatures/magento.py
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 3
    shodan-query: http.component:"Magento"
  tags: magento,exposure,credential,config
traps:
- request:
    method: GET
    path: /app/etc/local.xml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '* Magento<dbname>'
- request:
    method: GET
    path: /app/etc/local.xml.additional
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /store/app/etc/local.xml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
