id: mercurial-hgignore
info:
  name: Mercurial Ignore - File Disclosure
  author: DhiyaneshDK
  description: Mercurial Ignore file disclosure was detected.
  severity: info
  reference:
  - https://swcarpentry.github.io/hg-novice/08-ignore/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"hgignore"
  tags: exposure,hgignore,config,mercurial
traps:
- request:
    method: GET
    path: /.hgignore
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
