id: netbeans-config
info:
  name: Netbeans Config - Detect
  author: sbani
  description: Netbeans configuration information was detected.
  severity: info
  reference:
  - https://netbeans.apache.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: netbeans,config,exposure
traps:
- request:
    method: GET
    path: /nbproject/project.properties
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: (?mi)^src.dir=(?mi)^build.[a-zA-Z]+=(?mi)^jar.[a-zA-Z]+=
