id: netrc
info:
  name: Netrc - Config File Discovery
  author: geeknik
  description: Netrc configuration file was discovered.
  severity: high
  reference:
  - https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html
  metadata:
    max-request: 2
  tags: netrc,config,exposure
traps:
- request:
    method: GET
    path: /.netrc
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'machine [0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\.?login
      password '
- request:
    method: GET
    path: /_netrc
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
