id: nginx-config
info:
  name: Nginx Config - Detect
  author: sheikhrishad,geeknik
  description: Nginx configuration information was detected.
  severity: info
  reference:
  - https://nginx.org/en/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,nginx
traps:
- request:
    method: GET
    path: /nginx.conf
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: html>serverlistenserver_name
