id: oracle-ebs-credentials
info:
  name: Oracle E-Business System Credentials Page - Detect
  author: dhiyaneshDk
  description: Oracle E-Business System credentials page was detected.
  severity: high
  reference:
  - https://www.blackhat.com/docs/us-16/materials/us-16-Litchfield-Hackproofing-Oracle-eBusiness-Suite-wp-4.pdf
  - https://www.blackhat.com/docs/us-16/materials/us-16-Litchfield-Hackproofing-Oracle-eBusiness-Suite.pdf
  - http://www.davidlitchfield.com/AssessingOraclee-BusinessSuite11i.pdf
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,oracle
traps:
- request:
    method: GET
    path: /OA_HTML/jtfwrepo.xml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: password=<PUSR_LIST>
