id: ovpn-config-exposed
info:
  name: OVPN Configuration Download Page - Detect
  author: tess
  description: OVPS configuration download page was detected.
  severity: low
  classification:
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"OVPN Config Download"
  tags: config,ovpn,exposure
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: OVPN Config DownloadConfig List
