id: owncloud-config
info:
  name: owncloud Config - Detect
  author: Mahendra Purbia (Mah3Sec_)
  description: owncloud configuration information was detected.
  severity: info
  reference:
  - https://owncloud.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure
traps:
- request:
    method: GET
    path: /owncloud/config/
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Index ofowncloud/config
