id: pipfile-config
info:
  name: Pipfile Config - Detect
  author: DhiyaneshDK
  description: Pipfile configuration information was detected.
  severity: info
  reference: https://pypi.org/project
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Pipfile"
  tags: exposure,pip,devops,cicd
traps:
- request:
    method: GET
    path: /Pipfile
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '[[source]][packages]'
