id: pre-commit-config
info:
  name: Pre-commit Configuration File - Detect
  author: DhiyaneshDk
  description: Pre-commit configuration file was detected.
  severity: info
  reference: https://pre-commit.com/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
  tags: exposure,devops,config,cicd
traps:
- request:
    method: GET
    path: /.pre-commit-config.yaml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'repos:hooks:rev:'
- request:
    method: GET
    path: /pre-commit-config.yaml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
