id: procfile-config
info:
  name: Procfile Config - Detect
  author: DhiyaneshDK
  description: Procfile configuration information was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Procfile"
  tags: devops,exposure,config
traps:
- request:
    method: GET
    path: /Procfile
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '^web:'
