id: proftpd-config
info:
  name: ProFTPD Configuration File - Detect
  author: sheikhrishad
  description: ProFTPD configuration file was detected.
  severity: info
  reference: http://www.proftpd.org/docs/howto/ConfigFile.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,proftpd
traps:
- request:
    method: GET
    path: /proftpd.conf
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ProFTPDServerName
