id: proxy-wpad-exposure
info:
  name: Web Proxy Auto-Discovery Configuration File - Detect
  author: DhiyaneshDk
  description: Web Proxy Auto-Discovery configuration file was detected.
  severity: info
  reference: https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"wpad.dat"
  tags: config,exposure,proxy
traps:
- request:
    method: GET
    path: /wpad.dat
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: FindProxyForURLurlhost
