id: psalm-config
info:
  name: Psalm Configuration Exposure - Detect
  author: DhiyaneshDK
  description: 'Psalm configuration page was detected.

    '
  severity: low
  reference:
  - https://psalm.dev/docs/running_psalm/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"psalm.xml"
  tags: devops,exposure,php,psalm,config
traps:
- request:
    method: GET
    path: /psalm.xml
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: application/xml
    body: <psalm<projectFilesxmlns:xsi
