id: pubspec-config
info:
  name: Pubspec YAML Configuration File - Detect
  author: DhiyaneshDk
  description: Pubspec YAML configuration file was detected.
  severity: info
  reference:
  - https://docs.flutter.dev/development/tools/pubspec
  - https://xeladu.medium.com/the-flutter-pubspec-yaml-in-detail-eee5729d9df7
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"pubspec.yaml"
  tags: exposure,devops,pubsec,config,cicd
traps:
- request:
    method: GET
    path: /pubspec.yaml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'version:environment:dependencies:'
- request:
    method: GET
    path: /assets/pubspec.yaml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
