id: pyproject-toml
info:
  name: pyproject.toml Configuration - Detect
  author: DhiyaneshDK
  description: pyproject.toml configuration was detected.
  severity: info
  reference: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"pyproject.toml"
  tags: exposure,pyproject,pip,devops,cicd
traps:
- request:
    method: GET
    path: /pyproject.toml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '[tool.black]exclude =[tool.poetry]name ='
