id: rackup-config-ru
info:
  name: Rackup Configuration - Detect
  author: DhiyaneshDk
  description: Rackup configuration information was detected.
  severity: info
  reference:
  - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
  - https://learn.co/lessons/config-ru-tutorial
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"config.ru"
  tags: exposure,files,config,rackup
traps:
- request:
    method: GET
    path: /config.ru
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: run Rails.application/config/environmentBundler.requirerequire 'rubygems'
