id: rails-database-config
info:
  name: Ruby on Rails Database Configuration File - Detect
  author: pdteam,geeknik
  description: Ruby on Rails database configuration file was detected, which may contain
    database credentials.
  severity: high
  reference: https://guides.rubyonrails.org/configuring.html#configuring-a-database
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,rails
traps:
- request:
    method: GET
    path: /config/database.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'adapter:database:production:'
