id: robomongo-credential
info:
  name: RoboMongo Configuration File - Detect
  author: geeknik
  description: A MongoDB credentials file used by RoboMongo was detected.
  severity: high
  reference: https://robomongo.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: mongodb,robomongo,disclosure,config,exposure
traps:
- request:
    method: GET
    path: /db/robomongo.json
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: application/json
    body: databaseNameuserNameuserPasswordserverHost
- request:
    method: GET
    path: /robomongo.json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
