id: rollup-js-config
info:
  name: Rollup.js Configuration - Detect
  author: DhiyaneshDK
  description: Rollup configuration was detected.
  severity: info
  reference:
  - https://rollup.docschina.org/guide/en/#configuration-files
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"rollup.config.js"
  tags: exposure,devops,cicd,rollupjs
traps:
- request:
    method: GET
    path: /rollup.config.js
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'export default [input:'
