id: rubocop-config
info:
  name: Rubocop Configuration - Detect
  author: DhiyaneshDk
  description: Rubocop configuration information was detected.
  severity: info
  reference:
  - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
  - https://github.com/rubocop/rubocop
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"rubocop.yml"
  tags: exposure,files,config,ruby
traps:
- request:
    method: GET
    path: /.rubocop.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'AllCops:Include:Exclude:'
