id: s3cmd-config
info:
  name: S3CMD Configuration - Detect
  author: Ice3man
  description: S3CMD configuration information was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: amazon,config,exposure
traps:
- request:
    method: GET
    path: /s3cmd.ini
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '[default]access_key'
