id: samba-config
info:
  name: Samba Config - Detect
  author: sheikhrishad
  description: Samba configuration information was detected.
  severity: info
  reference: https://www.samba.org/samba/docs/using_samba/ch06.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,smb,samba
traps:
- request:
    method: GET
    path: /smb.conf
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: configuration filesamba
