id: sftp-credentials-exposure
info:
  name: SFTP Configuration File - Credentials Exposure
  author: geeknik,sheikhrishad
  description: SFTP configuration file was detected.
  severity: high
  reference:
  - https://blog.sucuri.net/2012/11/psa-sftpftp-password-exposure-via-sftp-config-json.html
  - https://www.acunetix.com/vulnerabilities/web/sftp-ftp-credentials-exposure/
  - https://codexns.io/products/sftp_for_sublime/settings
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    github-query: filename:sftp-config.json
  tags: sftp,config,exposure
traps:
- request:
    method: GET
    path: /sftp-config.json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"host":"user":"password":"remote_path":file_permissionsextra_list_connections'
- request:
    method: GET
    path: /ftpsync.settings
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
