id: ssh-known-hosts
info:
  name: SSH Known Hosts File - Detect
  author: geeknik
  description: SSH known hosts file was detected.
  severity: info
  reference:
  - https://datacadamia.com/ssh/known_hosts
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure,ssh
traps:
- request:
    method: GET
    path: /.ssh/known_hosts
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ssh-dssssh-ed25519ssh-rsaecdsa-sha2-nistp256
- request:
    method: GET
    path: /.ssh/known_hosts.old
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
