id: stestr-config
info:
  name: Stestr Configuration File - Detect
  author: Hardik-Solanki
  description: Stestr configuration file was detected.
  severity: info
  reference:
  - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
  - https://stestr.readthedocs.io/en/latest/MANUAL.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    github-query: filename:stestr.conf
  tags: exposure,stestr,config,files
traps:
- request:
    method: GET
    path: /.stestr.conf
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '[DEFAULT]test_path='
