id: symfony-profiler
info:
  name: Symfony Profiler - Detect
  author: pdteam
  description: Symfony profiler was detected.
  severity: high
  reference: https://symfony.com/doc/current/profiler.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
    shodan-query: http.html:"symfony Profiler"
  tags: config,exposure,symfony
traps:
- request:
    method: GET
    path: /_profiler/empty/search/results?limit=10
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Symfony Profiler<title>Profiler</title>
- request:
    method: GET
    path: /app_dev.php/_profiler/empty/search/results?limit=10
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
