id: symfony-database-config
info:
  name: Symfony Database Configuration File - Detect
  author: pdteam,geeknik
  description: Symfony database configuration file was detected and may contain database
    credentials.
  severity: high
  reference: https://symfony.com/legacy/doc/reference/1_3/en/07-Databases
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,symfony
traps:
- request:
    method: GET
    path: /config/databases.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: text/html
    body: 'class:param:'
