id: web-config
info:
  name: Web Configuration File - Detect
  author: Yash Anand @yashanand155,DhiyaneshDK
  description: Web configuration file was detected.
  severity: info
  reference:
  - https://github.com/imhunterand/ApachSAL/blob/main/assets/exploits.json
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure
traps:
- request:
    method: GET
    path: /web.config
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <configuration><system.webServer>
- request:
    method: GET
    path: /../../web.config
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
