id: websheets-config
info:
  name: Websheets Configuration File - Detect
  author: geeknik
  description: Websheets configuration file was detected.
  severity: high
  reference:
  - https://github.com/daveagp/websheets
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 2
  tags: websheets,config,exposure,files
traps:
- request:
    method: GET
    path: /ws-config.json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"db-password":"db-database":'
- request:
    method: GET
    path: /ws-config.example.json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
