id: wordpress-accessible-wpconfig
info:
  name: WordPress wp-config Detection
  author: Kiblyn11,zomsop82,madrobot,geeknik,daffainfo,r12w4n,tess,0xpugazh,mastercho
  description: WordPress `wp-config` was discovered. This file is remotely accessible
    and its content available for reading.
  severity: medium
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 30
  tags: wordpress,backup
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: DB_NAMEDB_PASSWORDDBNAMEPASSWORDDB_USERNAMEDB_PASSWORD
