id: bitbucket-pipelines
info:
  name: BitBucket Pipelines Configuration Exposure
  author: DhiyaneshDK
  description: null
  severity: info
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"bitbucket-pipelines.yml"
  tags: exposure,bitbucket,devops,cicd,files
traps:
- request:
    method: GET
    path: /bitbucket-pipelines.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'pipelines:step:'
