id: cloud-config
info:
  name: Cloud Config File Exposure
  author: DhiyaneshDK,Hardik-Solanki
  description: Cloud Config file is exposed.
  severity: medium
  reference: https://www.exploit-db.com/ghdb/7959
  metadata:
    verified: true
    max-request: 3
    shodan-query: html:"cloud-config.yml"
  tags: exposure,cloud,devops,files
traps:
- request:
    method: GET
    path: /cloud-config.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ssh_authorized_keys#cloud-config
- request:
    method: GET
    path: /core-cloud-config.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /cloud-config.txt
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
