id: environment-rb
info:
  name: Environment Ruby File Disclosure
  author: DhiyaneshDK
  description: Ruby environment file is exposed.
  severity: medium
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" "environment.rb"
  tags: ruby,devops,exposure,files
traps:
- request:
    method: GET
    path: /environment.rb
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '# Load the Rails application.'
- request:
    method: GET
    path: /config/environment.rb
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /redmine/config/environment.rb
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
