id: pipeline-configuration
info:
  name: Pipeline Configuration Exposure
  author: DhiyaneshDK
  description: null
  severity: info
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"pipeline.yaml"
  tags: devops,exposure,cicd,files
traps:
- request:
    method: GET
    path: /pipeline.yaml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'system:project_name:'
