id: redmine-config
info:
  name: Redmine Configuration File - Detect
  author: DhiyaneshDK
  description: Redmine configuration file was detected.
  severity: high
  reference:
  - https://www.exploit-db.com/ghdb/5803
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" configuration.yml
  tags: exposure,redmine,devops,edb,files
traps:
- request:
    method: GET
    path: /configuration.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: user_namepasswordRedmine
- request:
    method: GET
    path: /config/configuration.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /redmine/config/configuration.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
