id: redmine-settings
info:
  name: Redmine settings.yml File Disclosure
  author: DhiyaneshDK
  description: null
  severity: info
  reference: https://www.exploit-db.com/ghdb/5796
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" "settings.yml"
  tags: misconfig,redmine,devops,files,exposure
traps:
- request:
    method: GET
    path: /settings.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: format:default:Redmine
- request:
    method: GET
    path: /config/settings.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /redmine/config/settings.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
