id: symfony-security
info:
  name: Symfony security.yml File Disclosure
  author: DhiyaneshDK
  description: null
  severity: info
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" "security.yml"
  tags: symfony,devops,exposure,files
traps:
- request:
    method: GET
    path: /security.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'security:providers:'
- request:
    method: GET
    path: /config/security.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
- request:
    method: GET
    path: /app/config/security.yml
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
