id: xampp-environment-variables
info:
  name: XAMPP Environment Variables Exposure
  author: melbadry9,DhiyaneshDK
  description: printenv.pl file is exposed in XAMPP leaking environment variables.
  severity: low
  metadata:
    max-request: 1
  tags: exposure,xampp,files
traps:
- request:
    method: GET
    path: /cgi-bin/printenv.pl
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '<TITLE>Environment Variables</TITLE>Environment Variables:'
