id: dlink-config-dump
info:
  name: D-Link DAP-1325 - Information Disclosure
  author: gy741
  description: 'Security vulnerability known as Unauthenticated access to settings
    or Unauthenticated configuration download. This vulnerability occurs when a device,
    such as a repeater, allows the download of user settings without requiring proper
    authentication.

    '
  severity: critical
  reference:
  - https://www.exploit-db.com/exploits/51556
  - https://www.dropbox.com/s/eqz0ntlzqp5472l/DAP-1325.mp4?dl=0
  metadata:
    max-request: 1
    shodan-query: title:"D-LINK"
  tags: misconfig,config,dump,dlink,auth-bypass,disclosure
traps:
- request:
    method: GET
    path: /cgi-bin/ExportSettings.sh
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: filename="(.*)_Settings.datapplication/octet-stream
    body: Password
