id: misconfigured-docker
info:
  name: Docker Container - Misconfiguration Exposure
  author: dhiyaneshDK
  description: A Docker container misconfiguration was discovered. The Docker daemon
    can listen for Docker Engine API requests via three different types of Socket
    - unix, tcp, and fd. With tcp enabled, the default setup provides un-encrypted
    and un-authenticated direct access to the Docker daemon. It is conventional to
    use port 2375 for un-encrypted, and port 2376 for encrypted communication with
    the daemon.
  severity: critical
  reference:
  - https://madhuakula.com/content/attacking-and-auditing-docker-containers-using-opensource/attacking-docker-containers/misconfiguration.html
  metadata:
    max-request: 1
  tags: misconfig,docker,unauth,devops
traps:
- request:
    method: GET
    path: /images/json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"ParentId":"Containers":"Labels":'
