id: typo3-composer
info:
  name: Typo3 composer.json Exposure
  author: 0x_Akoko
  description: 'The web application is based on Typo3 CMS. A sensitive file has been
    found. Access to such files must be restricted, as it may lead to disclosure of
    sensitive information about the web application.

    '
  severity: low
  reference:
  - https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.0/Breaking-83302-ComposerRestrictsInstallationOfTypo3cms.html
  metadata:
    verified: true
    max-request: 1
    shodan-query: 'X-TYPO3-Parsetime: 0ms'
  tags: typo3,cms,exposure,misconfig
traps:
- request:
    method: GET
    path: /typo3/sysext/install/composer.json
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: The Install Tool mounted as the module Tools>Install in TYPO3.typo3-cms-framework
