id: kubernetes-metrics
info:
  name: Detect Kubernetes Exposed Metrics
  author: pussycat0x
  description: Information Disclosure of Garbage Collection
  severity: low
  reference:
  - https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes
  metadata:
    max-request: 1
  tags: kubernetes,exposure,devops,misconfig
traps:
- request:
    method: GET
    path: /metrics
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: namespaceHELPTYPEkube
