id: kubernetes-pods-api
info:
  name: Kubernetes Pods - API Discovery & Remote Code Execution
  author: ilovebinbash,geeknik,0xtavian
  description: A Kubernetes Pods API was discovered. When the service port is available,
    unauthenticated users can execute commands inside the container.
  severity: critical
  reference:
  - https://github.com/officialhocc/Kubernetes-Kubelet-RCE
  - https://blog.binaryedge.io/2018/12/06/kubernetes-being-hijacked-worldwide/
  metadata:
    max-request: 2
  tags: k8,unauth,kubernetes,devops,misconfig
traps:
- request:
    method: GET
    path: /pods
    headers: null
    body: null
  response:
    status_code: 200
    headers:
      VulTrap: application/json
    body: apiVersion
- request:
    method: GET
    path: /api/v1/pods
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: ''
