id: manageengine-applications-manager
info:
  name: ZOHO ManageEngine Applications Manager Panel - Detected
  author: dhiyaneshDK
  description: ZOHO ManageEngine panel was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:zohocorp:manageengine_applications_manager:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: manageengine_applications_manager
    vendor: zohocorp
  tags: panel,zoho,manageengine,zohocorp
traps:
- request:
    method: GET
    path: /index.do
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: <title>Applications Manager Login Screen</title>
