id: manageengine-network-config
info:
  name: Zoho ManageEngine Network Configuration Manager Panel - Detect
  author: righettod
  description: ZOHO ManageEngine Network Configuration Manager was detected.
  severity: info
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:zohocorp:manageengine_network_configuration_manager:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    product: manageengine_network_configuration_manager
    shodan-query: http.title:"Network Configuration Manager"
    vendor: zohocorp
    verified: true
  tags: panel,zoho,manageengine,zohocorp
traps:
- request:
    method: GET
    path: /apiclient/ember/Login.jsp
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: Network Configuration Managerhttps://www.manageengine.com
