id: prometheus-config
info:
  name: Prometheus Config API Endpoint Discovery
  author: geeknik
  description: A Prometheus config API endpoint was discovered. The config endpoint
    returns the loaded Prometheus configuration file along with the addresses of targets
    and alerting/discovery services alongside the credentials required to access them.
    Usually, Prometheus replaces the passwords in the credentials config configuration
    field with the placeholder <secret> (although this still leaks the username).
  severity: info
  reference:
  - https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  metadata:
    max-request: 1
  tags: prometheus,config,misconfig
traps:
- request:
    method: GET
    path: /api/v1/status/config
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"status": "success":"data":"yaml":'
