id: prometheus-targets
info:
  name: Prometheus targets API endpoint
  author: geeknik
  description: The targets endpoint exposes services belonging to the infrastructure,
    including their roles and labels. In addition to showing the target machine addresses,
    the endpoint also exposes metadata labels that are added by the target provider.
    These labels are intended to contain non-sensitive values, like the name of the
    server or its description, but various cloud platforms may automatically expose
    sensitive data in these labels, oftentimes without the developer's knowledge.
  severity: info
  reference:
  - https://jfrog.com/blog/dont-let-prometheus-steal-your-fire/
  metadata:
    max-request: 1
  tags: prometheus,misconfig
traps:
- request:
    method: GET
    path: /api/v1/targets
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: '"status": "success""data":"labels":'
