id: netlify-takeover
info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  description: netlify takeover was detected.
  severity: high
  reference:
  - https://github.com/EdOverflow/can-i-take-over-xyz/issues/40
  - https://monish-basaniwal.medium.com/how-i-found-my-first-subdomain-takeover-vulnerability-b7d5c17b61fd
  - https://github.com/EdOverflow/can-i-take-over-xyz/pull/289
  metadata:
    max-request: 1
  tags: takeover,netlify
traps:
- request:
    method: GET
    path: ''
    headers: null
    body: null
  response:
    status_code: 200
    headers: {}
    body: 'Not Found - Request ID:'
